<?= $this->extend('layouts/sidebar') ?>

<?= $this->section('title') ?>
Daftar Acara
<?= $this->endSection() ?>

<?= $this->section('content') ?>
<?= $this->include('layouts/header') ?>

<head>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
</head>

<div class="custom-container mt-3">
    <h4>Daftar Acara</h4>
    <style>
        .custom-container{
            font-family: 'Poppins', sans-serif;
            background-color: #fff;
            margin: 15px;
            border: 1px solid #D9D9D9;
            padding: 50px;
            width: 98%;
        }
        /* Styling untuk masing-masing tombol */
        .btn-custom {
            margin-right: 10px; /* Jarak antar tombol */
            border-radius: 10px; /* Border radius */
            border: 1px solid transparent; /* Tambahkan border */
        }

        /* Styling tombol sesuai tema */
        .btn-primary-custom {
            background-color: #02347e;
            color: white;
            border-color: #02347e;
        }

        .btn-success-custom {
            background-color: #1d6f42;
            color: white;
            border-color: #1d6f42;
        }

        .btn-danger-custom {
            background-color: #960019;
            color: white;
            border-color: #960019;
        }

        /* Styling untuk input search */
        .search-input {
            border-radius: 15px;
            padding: 0.375rem 1.75rem;
            width: 200px;
            border: 1px solid #ced4da;
        }

        /* Styling table */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 2px solid #000;
        }

        .custom-th{
            background-color: #02347e;
            color: white;
        }
        th {
            background-color: #02347e;
            text-align: center;
            padding: 10px;
        }

        td {
            padding: 10px;
            text-align: center;
        }

        .btn-info{
            background-color: #02347e;
            color:white;
        }

        /* Styling pagination */
        .pagination {
            justify-content: flex-end;
            margin-top: 20px;
        }

        .page-item.active .page-link {
            background-color: #007bff;
            border-color: #007bff;
        }
    </style>
<div class="box-table">
    <div class="d-flex justify-content-between mb-3 mt-3">
        <!-- Tambah dan Download Buttons -->
        <div class="d-inline-block">
            <a href="/kegiatan/create" class="btn btn-primary btn-custom btn-primary-custom">Tambah</a>
            <a href="/download/excel" class="btn btn-success btn-custom btn-success-custom">Download Excel</a>
            <a href="/download/pdf" class="btn btn-danger btn-custom btn-danger-custom">Download PDF</a>
        </div>

        <!-- Search Form -->
        <input type="text" id="searchInput" class="form-control search-input" placeholder="Search">
    </div>


    <!-- Table -->
    <table class="table table-bordered table-hover" id="kegiatan">
        <thead>
            <tr class="custom-th">
                <th>No</th>
                <th>Nama Acara</th>
                <th>PIC</th>
                <th>Tim</th>
                <th>Lokasi</th>
                <th>Waktu</th>
                <th>Status</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($kegiatan as $row): ?>
            <tr>
                <td><?= $row['id_acara']; ?></td>
                <td><?= $row['nama_acara']; ?></td>
                <td><?= $row['pic']; ?></td>
                <td><?= $row['tim_tugas']; ?></td>
                <td><?= $row['lokasi']; ?></td>
                <td><?= $row['waktu_acara']; ?></td>
                <td><?= $row['status_kegiatan']; ?></td>
                <td>
                    <a href="/kegiatan/view/<?= $row['id_acara']; ?>" class="btn btn-info btn-sm">View</a>
                    <a href="/kegiatan/edit/<?= $row['id_acara']; ?>" class="btn btn-warning btn-sm">Edit</a>
                    <a href="/kegiatan/delete/<?= $row['id_acara']; ?>" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus acara ini?')">Delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="d-flex justify-content-end mt-5">
        <a href="pra_produksi" class="btn btn-secondary">Selanjutnya</a>
    </div>

    <!-- Pagination -->
    <nav id="paginationNav">
        <ul class="pagination">
            <!-- Pagination items will be generated by JavaScript -->
        </ul>
    </nav>
</div>

<!-- JavaScript -->
<script>
document.addEventListener('DOMContentLoaded', () => {
    const itemsPerPageSelect = document.getElementById('itemsPerPage');
    const searchInput = document.getElementById('searchInput');
    const kegiatan = document.getElementById('kegiatan');
    const tableRows = Array.from(kegiatan.querySelectorAll('tbody tr'));
    const paginationNav = document.getElementById('paginationNav');

    let itemsPerPage = parseInt(itemsPerPageSelect.value);
    let currentPage = 1;

    function updateTable() {
        // Get the search term
        const searchTerm = searchInput.value.toLowerCase();

        // Filter rows based on the search term
        const filteredRows = tableRows.filter(row => {
            const cells = row.getElementsByTagName('td');
            let match = false;
            for (let cell of cells) {
                if (cell.textContent.toLowerCase().includes(searchTerm)) {
                    match = true;
                    break;
                }
            }
            return match;
        });

        // Pagination
        const totalRows = filteredRows.length;
        const totalPages = Math.ceil(totalRows / itemsPerPage);

        // Show only rows for the current page
        const startIndex = (currentPage - 1) * itemsPerPage;
        const endIndex = startIndex + itemsPerPage;
        tableRows.forEach(row => row.style.display = 'none'); // Hide all rows
        filteredRows.slice(startIndex, endIndex).forEach(row => row.style.display = '');

        // Update pagination controls
        paginationNav.querySelector('ul').innerHTML = '';
        for (let i = 1; i <= totalPages; i++) {
            const pageItem = document.createElement('li');
            pageItem.className = 'page-item';
            pageItem.innerHTML = `<a class="page-link" href="#">${i}</a>`;
            pageItem.addEventListener('click', () => {
                currentPage = i;
                updateTable();
            });
            paginationNav.querySelector('ul').appendChild(pageItem);
        }

        // Highlight the current page
        paginationNav.querySelectorAll('.page-item').forEach(item => {
            item.classList.toggle('active', item.textContent.trim() == currentPage);
        });
    }

    // Event listeners
    itemsPerPageSelect.addEventListener('change', () => {
        itemsPerPage = parseInt(itemsPerPageSelect.value);
        currentPage = 1; // Reset to first page
        updateTable();
    });

    searchInput.addEventListener('input', updateTable);

    // Initial update
    updateTable();
});
</script>

<?= $this->endSection() ?>
